backend:
  name: git-gateway
local_backend: true
media_folder: static/assets
public_folder: /assets

collections:
  - name: news
    label: News
    label_singular: News Item
    folder: content/news
    create: true
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: summary, label: Summary }
      - { name: content_html, label: Content, widget: markdown }
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: image_alt, label: Image Alt }
      - { name: date, label: Date Posted, widget: datetime }
  - name: plugins
    label: Plugins
    label_singular: Plugin
    folder: content/plugins
    create: true
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: content_html, label: Content, widget: markdown }
      - label: "Image"
        name: "image_url"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { name: image_alt, label: Image Alt }

  - name: about
    label: About Us
    label_singular: Content
    folder: content/about
    create: true
    extension: json
    fields:
      - label: "Title"
        name: "title"
      - label: "Content Items"
        label_singular: "Item"
        name: "content"
        widget: "list"
        fields:
        - { name: title, label: Title }
        - { name: content_html, label: Content, widget: markdown }
      - label: "Directors"
        name: "directors"
        widget: "object"
        fields:
          - { name: dir_one_name, label: Director 1 Name }
          - { name: dir_one_bio, label: Bio, widget: markdown }
          - label: "Image"
            name: "image_one_url"
            widget: "image"
            media_library:
              config:
                multiple: false

          - { name: dir_two_name, label: Director 2 Name }
          - { name: dir_two_bio, label: Bio, widget: markdown }
          - label: "Image"
            name: "image_two_url"
            widget: "image"
            media_library:
              config:
                multiple: false
      - label: "Contributors"
        name: "contributors"
        widget: "list"
        fields:
          - { name: title, label: Name }
          - label: "Image"
            name: "image_url"
            widget: "image"
            media_library:
              config:
                multiple: false

  - name: developers
    label: Developers Page
    label_singular: Content
    folder: content/developers
    create: false
    extension: json
    fields:
      - { name: title, label: Title }
      - { name: content_html, label: Content, widget: markdown }
  
  - name: microsites
    label: Microsites
    label_singular: Microsite
    folder: content/microsites
    create: true
    extension: json
    fields:
      - { name: title, Label: Title}
      - { name: description, Label: Description, widget: markdown }
      - label: Sections
        label_singular: Section
        name: content
        widget: list
        fields:
          - { name: title, Label: Title }
          - label: Paragraphs
            label_singular: Paragraph
            name: paragraphs
            widget: list
            fields:
              - { name: title, Label: Title}
              - { name: content_html, Label: Content, widget: markdown }
     
      - label: Key Terms
        label_singular: Term
        name: Terms
        widget: list
        fields:
          - { name: title, Label: Term }
          - { name: description, Label: Description }
      

  - name: getInvolved
    label: Get Involved
    label_singular: Page
    folder: content/get-involved
    create: true
    extension: json
    fields:
      - { name: title, Label: Title}
      - { name: description, Label: Description }
      - label: Paragraphs
        label_singular: Paragraph
        name: content
        widget: list
        fields:
          - { name: title, Label: Title }
          - { name: content_html, Label: Content, widget: markdown }